# Generated by Django 2.0.4 on 2018-04-13 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_address_id', models.IntegerField(blank=True, default=None, null=True)),
                ('old_operator_id', models.IntegerField(blank=True, default=None, null=True)),
                ('old_client_id', models.IntegerField(blank=True, default=None, null=True)),
                ('old_branch_id', models.IntegerField(blank=True, default=None, null=True)),
                ('sort', models.CharField(blank=True, max_length=11, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('print_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_addr', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('phone2', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile2', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile3', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, default='howard.coural.co.nz', max_length=254, null=True)),
                ('email2', models.EmailField(blank=True, default='howard.coural.co.nz', max_length=254, null=True)),
                ('email3', models.EmailField(blank=True, default='howard.coural.co.nz', max_length=254, null=True)),
                ('bank_num', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_num', models.CharField(blank=True, max_length=20, null=True)),
                ('mail_type', models.CharField(blank=True, max_length=1, null=True)),
                ('card_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('alt_mail_type', models.CharField(blank=True, max_length=1, null=True)),
                ('alt_email', models.CharField(blank=True, max_length=50, null=True)),
                ('alt_fax', models.CharField(blank=True, max_length=50, null=True)),
                ('netpass', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdressSupp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('po_box', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CfgAddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CfgAdressSuppType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CfgJobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_price_id', models.IntegerField(default=0)),
                ('pa_dist', models.FloatField(blank=True, null=True)),
                ('pa_sdist', models.FloatField(blank=True, null=True)),
                ('pa_cont', models.FloatField(blank=True, null=True)),
                ('pr_u_1', models.FloatField(blank=True, null=True)),
                ('pr_u_2', models.FloatField(blank=True, null=True)),
                ('pr_u_3', models.FloatField(blank=True, null=True)),
                ('pr_u_4', models.FloatField(blank=True, null=True)),
                ('pr_u_5', models.FloatField(blank=True, null=True)),
                ('pr_u_6', models.FloatField(blank=True, null=True)),
                ('from_weight', models.FloatField(blank=True, null=True)),
                ('to_weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_files.Island')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField(blank=True, default=None, null=True)),
                ('rd', models.CharField(blank=True, max_length=255, null=True)),
                ('post_code', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pmp_areacode', models.IntegerField(blank=True, null=True)),
                ('pmp_runcode', models.IntegerField(blank=True, null=True)),
                ('lifestyle', models.IntegerField(blank=True, null=True)),
                ('farmers', models.IntegerField(blank=True, null=True)),
                ('dairies', models.IntegerField(blank=True, null=True)),
                ('sheep', models.IntegerField(blank=True, null=True)),
                ('beef', models.IntegerField(blank=True, null=True)),
                ('sheepbeef', models.IntegerField(blank=True, null=True)),
                ('dairybeef', models.IntegerField(blank=True, null=True)),
                ('hort', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('seq_region', models.IntegerField(blank=True, null=True)),
                ('seq_area', models.IntegerField(blank=True, null=True)),
                ('seq_code', models.IntegerField(blank=True, null=True)),
                ('is_hidden', models.CharField(max_length=2)),
                ('num_nzfw', models.IntegerField(blank=True, null=True)),
                ('rmt', models.IntegerField(blank=True, null=True)),
                ('rm_rr', models.IntegerField(blank=True, null=True)),
                ('rm_f', models.IntegerField(blank=True, null=True)),
                ('rm_d', models.IntegerField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_files.Area')),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_files.Island')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_files.Region')),
            ],
        ),
        migrations.CreateModel(
            name='RouteAff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master_files.Address')),
                ('invoice_details', models.TextField(blank=True, null=True)),
                ('c_code', models.IntegerField(blank=True, null=True)),
                ('has_discount', models.BooleanField(default=False)),
                ('delivery_details', models.TextField(blank=True, null=True)),
                ('net_costs', models.CharField(blank=True, max_length=20, null=True)),
                ('base_price', models.CharField(blank=True, max_length=20, null=True)),
                ('linehaul', models.CharField(blank=True, max_length=20, null=True)),
                ('u_nw_1', models.TextField(blank=True, null=True)),
                ('u_nw_2', models.TextField(blank=True, null=True)),
                ('u_nw_3', models.TextField(blank=True, null=True)),
                ('u_nw_4', models.TextField(blank=True, null=True)),
                ('u_nw_5', models.TextField(blank=True, null=True)),
                ('u_nw_6', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
            ],
            bases=('master_files.address',),
        ),
        migrations.AddField(
            model_name='routeaff',
            name='lbm_contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lbm_conractor', to='master_files.Address'),
        ),
        migrations.AddField(
            model_name='routeaff',
            name='lbm_dist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lbm_dist', to='master_files.Address'),
        ),
        migrations.AddField(
            model_name='routeaff',
            name='lbm_dropoff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lbm_dropoff', to='master_files.Address'),
        ),
        migrations.AddField(
            model_name='routeaff',
            name='lbm_subdist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lbm_subdist', to='master_files.Address'),
        ),
        migrations.AddField(
            model_name='routeaff',
            name='pcl_contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcl_contractor', to='master_files.Address'),
        ),
        migrations.AddField(
            model_name='routeaff',
            name='pcl_dist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcl_dist', to='master_files.Address'),
        ),
        migrations.AddField(
            model_name='routeaff',
            name='pcl_dropoff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcl_dropoff', to='master_files.Address'),
        ),
        migrations.AddField(
            model_name='routeaff',
            name='pcl_subdist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pcl_subdist', to='master_files.Address'),
        ),
        migrations.AddField(
            model_name='routeaff',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_files.Route'),
        ),
        migrations.AddField(
            model_name='publication',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_files.Address'),
        ),
        migrations.AddField(
            model_name='clientprice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_files.Address'),
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_files.Region'),
        ),
        migrations.AddField(
            model_name='adresssupp',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_files.Address'),
        ),
        migrations.AddField(
            model_name='adresssupp',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master_files.CfgAdressSuppType'),
        ),
        migrations.AddField(
            model_name='address',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mother', to='master_files.Address'),
        ),
        migrations.AddField(
            model_name='address',
            name='typ',
            field=models.ManyToManyField(to='master_files.CfgAddressType'),
        ),
    ]
