# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='typ',
            field=models.ManyToManyField(to='master_files.CfgAddressType'),
        ),
    ]
