# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_files', '0002_address_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='card_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='rate_red_fact',
            field=models.FloatField(default=1.0),
        ),
    ]
