# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_files', '0003_auto_20161213_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='fax',
            new_name='mobile3',
        ),
        migrations.RemoveField(
            model_name='address',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='address',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='address',
            name='latest_dep',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user_id',
        ),
        migrations.AddField(
            model_name='address',
            name='email2',
            field=models.EmailField(blank=True, default='howard.coural.co.nz', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='email3',
            field=models.EmailField(blank=True, default='howard.coural.co.nz', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='print_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='shares_eoy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
