# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_files', '0003_remove_address_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
