# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_files', '0005_auto_20161201_0057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RD',
        ),
        migrations.AddField(
            model_name='address',
            name='old_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='old_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='old_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='old_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
