# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_files', '0006_auto_20161215_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_price_id', models.IntegerField(default=0)),
                ('pa_dist', models.FloatField(blank=True, null=True)),
                ('pa_sdist', models.FloatField(blank=True, null=True)),
                ('pa_cont', models.FloatField(blank=True, null=True)),
                ('pr_u_1', models.FloatField(blank=True, null=True)),
                ('pr_u_2', models.FloatField(blank=True, null=True)),
                ('pr_u_3', models.FloatField(blank=True, null=True)),
                ('pr_u_4', models.FloatField(blank=True, null=True)),
                ('pr_u_5', models.FloatField(blank=True, null=True)),
                ('pr_u_6', models.FloatField(blank=True, null=True)),
                ('from_weight', models.FloatField(blank=True, null=True)),
                ('to_weight', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_files.Address')),
            ],
        ),
    ]
