# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_files', '0007_auto_20161201_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='old_branch_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='old_client_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
