# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_files', '0008_auto_20161219_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='master_files.Address'),
        ),
    ]
