# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_files', '0010_remove_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default='hdzierz@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
