# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_files', '0012_auto_20161205_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, default='howard.coural.co.nz', max_length=254, null=True),
        ),
    ]
