# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lbm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island', models.CharField(max_length=3)),
                ('area', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pmp_areacode', models.IntegerField(blank=True, null=True)),
                ('pmp_runcode', models.IntegerField(blank=True, null=True)),
                ('num_lifestyle', models.IntegerField(blank=True, null=True)),
                ('num_farmers', models.IntegerField(blank=True, null=True)),
                ('num_dairies', models.IntegerField(blank=True, null=True)),
                ('num_sheep', models.IntegerField(blank=True, null=True)),
                ('num_beef', models.IntegerField(blank=True, null=True)),
                ('num_sheepbeef', models.IntegerField(blank=True, null=True)),
                ('num_dairybeef', models.IntegerField(blank=True, null=True)),
                ('num_hort', models.IntegerField(blank=True, null=True)),
                ('seq_region', models.IntegerField(blank=True, null=True)),
                ('seq_area', models.IntegerField(blank=True, null=True)),
                ('seq_code', models.IntegerField(blank=True, null=True)),
                ('is_hidden', models.CharField(max_length=2)),
                ('num_nzfw', models.IntegerField(blank=True, null=True)),
                ('rmt', models.IntegerField(blank=True, null=True)),
                ('rm_rr', models.IntegerField(blank=True, null=True)),
                ('rm_f', models.IntegerField(blank=True, null=True)),
                ('rm_d', models.IntegerField(blank=True, null=True)),
                ('code_basei', models.CharField(max_length=255)),
                ('code_rd', models.CharField(max_length=255)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lbm.Job')),
            ],
        ),
    ]
