# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lbm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_type', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('external', models.CharField(blank=True, max_length=5, null=True)),
                ('is_edited', models.CharField(blank=True, max_length=1, null=True)),
                ('version', models.CharField(blank=True, max_length=30, null=True)),
                ('bundle_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('orig_amt', models.IntegerField(blank=True, null=True)),
                ('alt_dropoff_id', models.IntegerField(blank=True, null=True)),
                ('dropoff_id', models.IntegerField(blank=True, null=True)),
                ('doff', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('dist_id', models.IntegerField(blank=True, null=True)),
                ('subdist_id', models.IntegerField(blank=True, null=True)),
                ('contractor_id', models.IntegerField(blank=True, null=True)),
                ('subdist_rate_red', models.FloatField(default=1)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lbm.Job')),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='code_basei',
        ),
        migrations.RemoveField(
            model_name='route',
            name='job',
        ),
        migrations.AddField(
            model_name='jobroute',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lbm.Route'),
        ),
    ]
