# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbm', '0008_remove_route_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
