# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lbm', '0009_route_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='address',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='client',
        ),
        migrations.DeleteModel(
            name='RD',
        ),
        migrations.RemoveField(
            model_name='route',
            name='area',
        ),
        migrations.RemoveField(
            model_name='route',
            name='island',
        ),
        migrations.RemoveField(
            model_name='route',
            name='region',
        ),
        migrations.AlterField(
            model_name='lbmjob',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_files.Client'),
        ),
        migrations.AlterField(
            model_name='lbmjob',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_files.Publication'),
        ),
        migrations.AlterField(
            model_name='lbmjobroute',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_files.Route'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Island',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
