# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbm', '0010_auto_20161130_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='lbmjob',
            name='old_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lbmjobroute',
            name='old_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
