# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbm', '0011_auto_20161201_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lbmjob',
            name='is_regular',
            field=models.BooleanField(default=False),
        ),
    ]
