# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbm', '0012_auto_20161201_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lbmjob',
            name='is_quote',
        ),
        migrations.AlterField(
            model_name='lbmjob',
            name='has_ni',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lbmjob',
            name='has_si',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lbmjob',
            name='is_att',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lbmjob',
            name='is_deliv_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lbmjob',
            name='is_ioa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lbmjob',
            name='is_job_details_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lbmjob',
            name='is_pay_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lbmjobroute',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
