# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbm', '0013_auto_20161205_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='lbmjob',
            name='print_advices',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
