# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbm', '0014_lbmjob_print_advices'),
    ]

    operations = [
        migrations.AddField(
            model_name='lbmjob',
            name='ex_depot_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lbmjob',
            name='linehaul_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lbmjob',
            name='qty_per_bundle_ni',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lbmjob',
            name='qty_per_bundle_si',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lbmjob',
            name='l_h_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='lbmjob',
            name='label_printed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lbmjob',
            name='manifest_created',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
