# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coural_legacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCCRouteAff',
            fields=[
                ('route_aff_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_id', models.IntegerField()),
                ('dist_id', models.IntegerField(blank=True, null=True)),
                ('subdist_id', models.IntegerField(blank=True, null=True)),
                ('contractor_id', models.IntegerField(blank=True, null=True)),
                ('dropoff_id', models.IntegerField(blank=True, null=True)),
                ('app_date', models.DateField(blank=True, null=True)),
                ('stop_date', models.DateField(blank=True, null=True)),
                ('env_dist_id', models.IntegerField(blank=True, null=True)),
                ('env_contractor_id', models.IntegerField(blank=True, null=True)),
                ('pc_dist_id', models.IntegerField(blank=True, null=True)),
                ('env_subdist_id', models.IntegerField(blank=True, null=True)),
                ('pc_contractor_id', models.IntegerField(blank=True, null=True)),
                ('env_dropoff_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'route_aff',
                'managed': False,
            },
        ),
    ]
