# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coural_legacy', '0002_lcaddress_lcaddresscopy_lcauthgroup_lcauthgrouppermissions_lcauthpermission_lcauthuser_lcauthusergro'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCRoute',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('island', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('rd', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pmp_areacode', models.IntegerField(blank=True, null=True)),
                ('pmp_runcode', models.IntegerField(blank=True, null=True)),
                ('num_lifestyle', models.IntegerField(blank=True, null=True)),
                ('num_farmers', models.IntegerField(blank=True, null=True)),
                ('num_dairies', models.IntegerField(blank=True, null=True)),
                ('num_sheep', models.IntegerField(blank=True, null=True)),
                ('num_beef', models.IntegerField(blank=True, null=True)),
                ('num_sheepbeef', models.IntegerField(blank=True, null=True)),
                ('num_dairybeef', models.IntegerField(blank=True, null=True)),
                ('num_hort', models.IntegerField(blank=True, null=True)),
                ('seq_region', models.IntegerField(blank=True, null=True)),
                ('seq_area', models.IntegerField(blank=True, null=True)),
                ('seq_code', models.IntegerField(blank=True, null=True)),
                ('is_hidden', models.CharField(max_length=2)),
                ('num_nzfw', models.IntegerField(blank=True, null=True)),
                ('rmt', models.IntegerField(blank=True, null=True)),
                ('rm_rr', models.IntegerField(blank=True, null=True)),
                ('rm_f', models.IntegerField(blank=True, null=True)),
                ('rm_d', models.IntegerField(blank=True, null=True)),
                ('code_rd', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'route',
                'managed': False,
            },
        ),
    ]
